routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/produtos');
});

Route::resource('produtos', 'ProductsController');

app/Models/Products.php
<?php

namespace tstprod\Models;

use Illuminate\Database\Eloquent\Model;

class Products extends Model
{
    protected $fillable = [
        'name', 'description',
    ];
}

app/Models/User.php
<?php

namespace tstprod\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace tstprod\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ProductsController.php
<?php

namespace tstprod\Http\Controllers;

use tstprod\Http\Requests\Product\StoreRequest;
use tstprod\Http\Requests\Product\UpdateRequest;

use tstprod\Models\Products;

class ProductsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Products::paginate(15);
        return view('products.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('products.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRequest $request)
    {
        try {
            $product = Products::create( $request->all() );
            return redirect()->route('produtos.index')->with([
                'status' => 'success',
                'msg'    => "Produto $product->name adicionado a base de dados"
            ]);
        }catch(\Exception $e) {
            return redirect()->route('produtos.index')->with([
                'status' => 'danger',
                'msg'    => "Ocorreu um erro no processamento. Tente novamente em alguns instantes."
            ]);
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        try {
            $product = Products::findOrFail( $id );
            return view('products.edit', compact('product'));
        }catch(\Exception $e) {
            return redirect()->route('products.index')->with([
                'status' => 'danger',
                'msg'    => "Produto inexistente"
            ]);
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(updateRequest $request, $id)
    {
        try {
            $product = Products::findOrFail( $id );
            $product->fill( $request->all() );
            $product->save();
            return redirect()->route('produtos.index')->with([
                'status' => 'warning',
                'msg'    => "Produto $product->name atualizado"
            ]);
        }catch(\Exception $e) {
            return redirect()->route('produtos.index')->with([
                'status' => 'danger',
                'msg'    => "Ocorreu um erro no processamento. Tente novamente em alguns instantes."
            ]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $product = Products::findOrFail( $id );
            $name    = $product->name;
            $product->delete();
            return redirect()->route('produtos.index')->with([
                'status' => 'warning',
                'msg'    => "Produto $name deletado"
            ]);
        }catch(\Exception $e) {
            return redirect()->route('produtos.index')->with([
                'status' => 'danger',
                'msg'    => "Ocorreu um erro no processamento. Tente novamente em alguns instantes."
            ]);
        }
    }
}

resources/views/layouts/base.blade.php
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

        <title>Cadastro de Produtos</title>
    </head>
    <body>
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-12 col-md-12 col-lg-12">
                    @yield('content')
                </div>
            </div>
        </div>

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>

resources/views/products/create.blade.php
@extends('adminlte::page')

@section('content')
    <div class="box">
        <div class="box-header">
            <h3 class="box-title">
                <i class="fa fa-fw fa-plus-circle"></i>
                Novo Produto
            </h3>
            <div class="box-tools pull-right">
                <!-- Buttons, labels, and many other things can be placed here! -->
                <!-- Here is a label for example -->
                <a role="button" class="btn btn-default" href="{{ route('produtos.index') }}">
                    <i class="fa fa-fw fa-arrow-left"></i>
                    Voltar
                </a>
            </div>
            <!-- /.box-tools -->
        </div>
        <div class="box-body">
            <form id="add-product-form" class="form-horizontal" action="{{ route('produtos.store') }}" method="POST">
                {{ csrf_field() }}
                <div class="form-group">
                    <label for="name" class="col-sm-2 control-label">Nome do Produto</label>
                    <div class="col-sm-4">
                        <input type="text" class="form-control" id="name" name="name" required>
                    </div>
                </div>
                <div class="form-group">
                    <label for="description" class="col-sm-2 control-label">Descrição</label>
                    <div class="col-sm-5">
                        <textarea class="form-control" id="description" name="description" required></textarea>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button
                                id="btn-process-form"
                                type="button"
                                class="btn btn-success"
                                data-loading-text="Processando requisição..."
                        >
                            Adicionar
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@stop

@section('js')
    <script>
        $('#btn-process-form').click(function (e) {
            $(this).button('loading');
            $('#add-product-form').submit();
        });
    </script>
@stop

resources/views/products/edit.blade.php
@extends('adminlte::page')

@section('content')
    <div class="box">
        <div class="box-header">
            <h3 class="box-title">
                <i class="fa fa-fw fa-edit"></i>
                Atualizar Produto {{ $product->name }}
            </h3>
            <div class="box-tools pull-right">
                <!-- Buttons, labels, and many other things can be placed here! -->
                <!-- Here is a label for example -->
                <a role="button" class="btn btn-default" href="{{ route('produtos.index') }}">
                    <i class="fa fa-fw fa-arrow-left"></i>
                    Voltar
                </a>
            </div>
            <!-- /.box-tools -->
        </div>
        <div class="box-body">
            <form class="form-horizontal" action="{{ route('produtos.update', ['id' => $product->id]) }}" method="POST">
                {{ csrf_field() }}
                {{ method_field('PUT') }}
                <div class="form-group">
                    <label for="name" class="col-sm-2 control-label">Nome do Produto</label>
                    <div class="col-sm-4">
                        <input type="text" class="form-control" id="name" name="name" value="{{ $product->name }}">
                    </div>
                </div>
                <div class="form-group">
                    <label for="description" class="col-sm-2 control-label">Descrição</label>
                    <div class="col-sm-5">
                        <textarea class="form-control" id="description" name="description">{{ $product->description }}</textarea>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-success">
                            Atualizar
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@stop

resources/views/products/index.blade.php
@extends('adminlte::page')

@section('content')
    <div class="box">
        <div class="box-header">
            <h3 class="box-title">
                <i class="fa fa-fw fa-shopping-basket"></i>
                Produtos
            </h3>
            <div class="box-tools pull-right">
                <!-- Buttons, labels, and many other things can be placed here! -->
                <!-- Here is a label for example -->
                <a role="button" class="btn btn-primary" href="{{ route('produtos.create') }}">
                    <i class="fa fa-fw fa-plus-circle"></i>
                    Novo Produto
                </a>
            </div>
            <!-- /.box-tools -->
        </div>
        <div class="box-body">
            <table class="table table-sm table-condensed table-bordered" id="products-table">
                <thead>
                    <tr>
                        <th>Nome</th>
                        <th>Descrição</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                @foreach( $products as $product )
                    <tr>
                        <td>{{ $product->name }}</td>
                        <td>{{ $product->description }}</td>
                        <td class="text-right">
                            <div class="btn-group btn-group-xs" role="group">
                                <a role="button" class="btn btn-default" title="editar" href="{{ route('produtos.edit', ['id' => $product->id]) }}">
                                    <i class="fa fa-fw fa-edit"></i>
                                </a>
                            </div>

                            <div class="btn-group btn-group-xs" role="group">
                                <button type="button" class="btn btn-danger" title="deletar" onclick="deleteProduct({{$product->id}})">
                                    <i class="fa fa-fw fa-trash"></i>
                                </button>
                            </div>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
    <form id="delete-form" method="POST">{{ csrf_field() }}{{ method_field('DELETE') }}</form>
@stop

@section('css')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-sweetalert/1.0.1/sweetalert.css" />
@stop
@section('js')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-sweetalert/1.0.1/sweetalert.js"></script>
    <script>
        function deleteProduct(id) {
            swal({
                    title: "Você tem certeza dessa ação?",
                    text: "O arquivo será permanentemente apagado da base de dados",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonClass: "btn-danger",
                    confirmButtonText: "Sim",
                    cancelButtonText: "Não",
                    closeOnConfirm: false,
                    closeOnCancel: false
                },
                function (isConfirm) {
                    if (isConfirm) {
                        var form = $('#delete-form');
                        form.attr('action', '/produtos/'+id);
                        console.log( form.attr('action') );
                        form.submit();
                    } else {
                        swal("Cancelado", "Produto não será apagado da base de dados", "error");
                    }
                });
        }


        $(document).ready(function(){
            $('#products-table').dataTable();
        });
    </script>
@stop